apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-2
  namespace: external-dns-2
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
        subst: ${TEST:-none}
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.1
        args:
        - --registry=txt
        - --txt-prefix=external-dns-
        - --txt-owner-id=k8s
        - --provider=rfc2136
        - (( concat "--rfc2136-zone=" $.subst.dns.server ))
        - --rfc2136-port=53
        - (( concat "--rfc2136-zone=" $.subst.dns.domain ))
        - (( concat "--rfc2136-tsig-secret=" $.subst.tsig ))
        - --rfc2136-tsig-secret-alg=hmac-sha256
        - --rfc2136-tsig-keyname=externaldns-key
        - --rfc2136-tsig-axfr
        - --source=ingress
        - (( concat "--domain-filter=" $.subst.dns.domain ))