apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/dns/
  - ../../location/ch-east/
patches:
- path: ../../common/patches/patch.yaml
  target:
    kind: Deployment